
var LANG_DATA = [
	{
		"title" : "ComDown",
		"msg_shutdown" : "Shut down",
		"msg_agent_download" : "Agent download",
		"msg_manual" : "manual",
		"msg_developer" : "developer",
		"msg_areyousure" : "Are you sure ?",
		"msg_nopcs" : "There are no PCs in operation.<div class='alert alert-warning'><strong>Tip</strong><br>1. Did you update your Comdown agent for PC to <a href=http://airpage.org/xe/comdown/ target=_top>the latest version</a> ? <br>2. Every devices must be connected to same router as PC.</div>",		
		"msg_pclist_updated" : "PC list is updated",
		"msg_shutdown_failed_try" : "Failed",
		"msg_off": "Off",
		"msg_shutting_down" : "... ",
		"edge_not_support" : "I'm sorry. Edge browser is not supported yet.\nFor this reason, you can turn of only your PC on this browser.\nCould you please use another web browser ?",
		"msg_need_updated" : "Please, update <a href=https://airpage.org/xe/comdown>ComDown Agent</a> on this PC",
		"msg_need_updated2" : "Please, update ComDown Agent on this PC",
		"msg_onoff_times" : "PC ON/OFF Times (In the last month)",
		"msg_run_times" : "Daily PC operation time (In the last month)",
		"msg_times" : "time",
		"msg_operation_time" : "Operation time",
		"msg_day" : "Day",
		"msg_menu_shutdown" : "Shutdown",
		"msg_menu_reboot" : "Reboot",
		"msg_menu_screenoff" : "Screen OFF",
		"msg_menu_logoff" : "LOG OFF",
		"msg_menu_suspend" : "Suspend Mode",
		"msg_menu_hibernates" : "Hibernates Mode",
		"msg_menu_cancel" : "Cancel"
	},
	{
		"title" : "컴다운",
		"msg_shutdown" : "종료하기",
		"msg_agent_download" : "에이전트 내려받기",
		"msg_manual" : "설명서",
		"msg_developer" : "개발자",
		"msg_areyousure" : "정말로 진행 할까요 ?",
		"msg_nopcs" : "사용중인 PC가 없습니다<div class='alert alert-warning'><strong>팁</strong><br>1. PC의 컴다운 에이전트를 <a href=http://airpage.org/xe/comdown/ target=_top>최신버전</a>으로 업데이트 하셨나요?<BR>2. 모든 기기는 동일한 공유기에 연결되어 있어야 합니다.</div>",		
		"msg_pclist_updated" : "PC 목록이 갱신되었습니다",
		"msg_shutdown_failed_try" : "실패",
		"msg_off": "종료됨",
		"msg_shutting_down" : "... ",
		"edge_not_support" : "죄송합니다.\n현재 EDGE 브라우저는 지원되지 않습니다. 이에, 로컬 PC만 종료가 가능합니다.\n다른 브라우저의 사용을 부탁드립니다.",
		"msg_need_updated" : "이 PC의 컴다운 에이전트를 <a href=https://airpage.org/xe/comdown>업데이트</a> 해 주세요.",
		"msg_need_updated2" : "이 PC의 컴다운 에이전트를 업데이트 해 주세요.",
		"msg_onoff_times" : "PC ON/OFF 횟수 (최근 한달간)",
		"msg_run_times" : "일별 PC 사용시간 (최근 한달간)",
		"msg_times" : "시간",
		"msg_operation_time" : "사용시간",
		"msg_day" : "일",
		"msg_menu_shutdown" : "종료하기",
		"msg_menu_reboot" : "다시시작하기",
		"msg_menu_screenoff" : "화면 끄기",
		"msg_menu_logoff" : "로그오프",
		"msg_menu_suspend" : "서스팬드 모드",
		"msg_menu_hibernates" : "하이버네이츠 모드",		
		"msg_menu_cancel" : "취소"
	}	
	];